--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-0+deb12u1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-0+deb12u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: schema_almoxarifado; Type: SCHEMA; Schema: -; Owner: am_admin
--

CREATE SCHEMA schema_almoxarifado;


ALTER SCHEMA schema_almoxarifado OWNER TO am_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: flyway_schema_history; Type: TABLE; Schema: schema_almoxarifado; Owner: am_admin
--

CREATE TABLE schema_almoxarifado.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE schema_almoxarifado.flyway_schema_history OWNER TO am_admin;

--
-- Name: itens; Type: TABLE; Schema: schema_almoxarifado; Owner: am_admin
--

CREATE TABLE schema_almoxarifado.itens (
    id bigint NOT NULL,
    codigo character varying(255),
    descricao character varying(255) NOT NULL,
    local_armazenado character varying(255) NOT NULL,
    marca character varying(255) NOT NULL,
    observacoes character varying(255),
    quantidade integer NOT NULL,
    unidade_de_medida character varying(255) NOT NULL,
    tipo_id bigint
);


ALTER TABLE schema_almoxarifado.itens OWNER TO am_admin;

--
-- Name: itens_id_seq; Type: SEQUENCE; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE schema_almoxarifado.itens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schema_almoxarifado.itens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimentacoes; Type: TABLE; Schema: schema_almoxarifado; Owner: am_admin
--

CREATE TABLE schema_almoxarifado.movimentacoes (
    id bigint NOT NULL,
    data_hora timestamp(6) without time zone NOT NULL,
    observacoes character varying(255),
    quantidade integer NOT NULL,
    tipo character varying(255),
    item_id bigint,
    user_id bigint,
    CONSTRAINT movimentacoes_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ENTRADA'::character varying, 'SAIDA'::character varying])::text[])))
);


ALTER TABLE schema_almoxarifado.movimentacoes OWNER TO am_admin;

--
-- Name: movimentacoes_id_seq; Type: SEQUENCE; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE schema_almoxarifado.movimentacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schema_almoxarifado.movimentacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tipos_de_itens; Type: TABLE; Schema: schema_almoxarifado; Owner: am_admin
--

CREATE TABLE schema_almoxarifado.tipos_de_itens (
    id bigint NOT NULL,
    descricao character varying(255) NOT NULL,
    nome character varying(255) NOT NULL
);


ALTER TABLE schema_almoxarifado.tipos_de_itens OWNER TO am_admin;

--
-- Name: tipos_de_itens_id_seq; Type: SEQUENCE; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE schema_almoxarifado.tipos_de_itens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schema_almoxarifado.tipos_de_itens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: schema_almoxarifado; Owner: am_admin
--

CREATE TABLE schema_almoxarifado.usuarios (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    nome character varying(255) NOT NULL,
    role character varying(255),
    senha character varying(255) NOT NULL,
    CONSTRAINT usuarios_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'ALUNO'::character varying, 'INSTRUTOR'::character varying])::text[])))
);


ALTER TABLE schema_almoxarifado.usuarios OWNER TO am_admin;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE schema_almoxarifado.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME schema_almoxarifado.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE ONLY schema_almoxarifado.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: itens itens_pkey; Type: CONSTRAINT; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE ONLY schema_almoxarifado.itens
    ADD CONSTRAINT itens_pkey PRIMARY KEY (id);


--
-- Name: movimentacoes movimentacoes_pkey; Type: CONSTRAINT; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE ONLY schema_almoxarifado.movimentacoes
    ADD CONSTRAINT movimentacoes_pkey PRIMARY KEY (id);


--
-- Name: tipos_de_itens tipos_de_itens_pkey; Type: CONSTRAINT; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE ONLY schema_almoxarifado.tipos_de_itens
    ADD CONSTRAINT tipos_de_itens_pkey PRIMARY KEY (id);


--
-- Name: usuarios ukkfsp0s1tflm1cwlj8idhqsad0; Type: CONSTRAINT; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE ONLY schema_almoxarifado.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE ONLY schema_almoxarifado.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: schema_almoxarifado; Owner: am_admin
--

CREATE INDEX flyway_schema_history_s_idx ON schema_almoxarifado.flyway_schema_history USING btree (success);


--
-- Name: movimentacoes fkgnnf7m82uyjny3rccmrww4uyx; Type: FK CONSTRAINT; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE ONLY schema_almoxarifado.movimentacoes
    ADD CONSTRAINT fkgnnf7m82uyjny3rccmrww4uyx FOREIGN KEY (item_id) REFERENCES schema_almoxarifado.itens(id);


--
-- Name: movimentacoes fkp47b4lu5lwiws1iqw5avrj6pk; Type: FK CONSTRAINT; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE ONLY schema_almoxarifado.movimentacoes
    ADD CONSTRAINT fkp47b4lu5lwiws1iqw5avrj6pk FOREIGN KEY (user_id) REFERENCES schema_almoxarifado.usuarios(id);


--
-- Name: itens fksh8qt98t6tjigpa8fwyw4x0y6; Type: FK CONSTRAINT; Schema: schema_almoxarifado; Owner: am_admin
--

ALTER TABLE ONLY schema_almoxarifado.itens
    ADD CONSTRAINT fksh8qt98t6tjigpa8fwyw4x0y6 FOREIGN KEY (tipo_id) REFERENCES schema_almoxarifado.tipos_de_itens(id);


--
-- PostgreSQL database dump complete
--

